#!/bin/bash

mkdir -p ~/.cache/lf
CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' \
    -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"
TYPE=$(/usr/bin/vendor_perl/mimetype -b "$1" )

case $TYPE in
    application/pdf)
        [ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
        chafa -f sixel -s "$2x$3" --animate false "$CACHE.jpg" ;;
    image/*)
        chafa -f sixel -s "$2x$3" --animate false "$1" ;;
    text/markdown)
        glow -s dark $1 ;;
    *)
        bat --color=always --style=plain --pager=never "$1" ;;
esac

exit 0
