#!/bin/bash

get_volume() {
    $(pamixer --get-mute) && echo 0 || pamixer --get-volume
}

get_icon() {
    vol=$(get_volume)
    if [[ $vol == 0 ]]; then
        echo 
    elif [[ $vol < 50 ]]; then
        echo 
    else
        echo 
    fi
}

case $1 in
    "--vol") get_volume ;;
    "--icon") get_icon ;;
    *) get_volume ;;
esac
