#!/bin/bash

get_volume() {
    vol=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
    if [[ $vol =~ .*"MUTED".* ]]; then
        echo 0.00
    else
        echo $vol | awk -F ' ' '{print $2}'
    fi
}

get_icon() {
    vol=$(get_volume)
    if [[ $vol == 0.00 ]]; then
        echo 
    elif [[ $vol < 0.50 ]]; then
        echo 
    else
        echo 
    fi
}

case $1 in
    "--vol") get_volume ;;
    "--icon") get_icon ;;
    *) get_volume ;;
esac
