[git_branch]
symbol = ''

[git_status]
format = '([$all_status$ahead_behind]($style) )'
modified = '!${count}'
untracked = '?${count}'
staged = '+${count}'
conflicted = '~${count}'
stashed = '*${count}'
ahead = '⇡${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
renamed = ''
deleted = ''
