#!/bin/bash

env=$(cat ~/.config/waybar/scripts/.env)
if [[ "$env" == "" ]]; then
    exit
fi
export $env

count=`curl -u eerii:${TOKEN} https://api.github.com/notifications | jq '. | length'`

if [[ "$count" != "0" ]]; then
    echo '{"text":'$count',"tooltip":"$tooltip","class":"$class"}'
fi
